// Package rlmcore provides CGO bindings to the rlm-core Rust library.
//
// This package bridges Go code to the rlm-core FFI, enabling:
// - SqliteMemoryStore for hypergraph memory
// - PatternClassifier for complexity detection
// - SmartRouter for query routing
// - TrajectoryEvent for observability
// - Epistemic verification
//
// Build requirements:
// - rlm-core built with --features ffi
// - librlm_core.dylib (macOS) or librlm_core.so (Linux) in library path
//
// Set RLM_USE_CORE=true to enable these bindings.
package rlmcore

/*
#cgo CFLAGS: -I${SRCDIR}/../../../loop/rlm-core/ffi/include
#cgo LDFLAGS: -L${SRCDIR}/../../../loop/rlm-core/target/release -lrlm_core

// Forward declarations - actual headers will be generated by rlm-core FFI
// #include "rlm_core.h"
*/
import "C"

import (
	"fmt"

	"github.com/rand/recurse/internal/config"
)

// Available returns true if rlm-core bindings are available and enabled.
func Available() bool {
	return config.UseRlmCore() && libraryLoaded()
}

// libraryLoaded checks if the rlm-core shared library can be loaded.
// This is a stub that will be implemented when the FFI is ready.
func libraryLoaded() bool {
	// TODO: Implement actual library loading check
	// For now, return false until FFI headers are generated
	return false
}

// Version returns the rlm-core library version.
func Version() (string, error) {
	if !Available() {
		return "", fmt.Errorf("rlm-core not available")
	}
	// TODO: Call C.rlm_core_version()
	return "0.0.0-stub", nil
}
